version: '3.8'
services:
  server:
    build: .
    command: uvicorn rag_chat_server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  frontend:
    build: .
    command: streamlit run --server.address=0.0.0.0 app.py
    ports:
      - "8501:8501"
